---

- name: supervisor start
  service: name=supervisor state=started

- name: supervisor stop
  service: name=supervisor state=stopped

- name: supervisor restart
  service: name=supervisor state=restarted

# vi:ts=2:sw=2:et:ft=yaml
